from enum import Enum

list_name_dict = {
    "salary_fixed_allowances_attributes": "m_fixed_allowance",
    "salary_variable_allowances_attributes": "m_variable_allowance",
    "salary_type_id": "m_salary_type",
    "overtime_salary_id": "m_overtime_salary",
    "exceeding_overtime_id": "m_exceeding_overtime",
    "overtime_excluded_object_id": "m_overtime_excluded_object",
    "salary_payment_method_id": "m_salary_payment_method",
    "working_hours_type_id": "m_working_hours_type",
    "discretionary_labor_system_type_id": "m_discretionary_labor_system_type",
    "office_work_id": "m_office_work",
    "variable_working_hours_type_id": "m_variable_working_hours_type",
    "contract_working_hours_system_id": "m_contract_working_hours_system",
    "occupational_category_ids": "m_occupational_category",
    "prefecture_ids": "m_prefecture",
    "future_workplace_id": "m_future_workplace",
    "transfer_id": "m_transfer",
    "remote_type_ids": "m_remote_type",
    "smoking_prevention_content_id": "m_smoking_prevention_content",
    "ids": "m_future_job_description",
    "allowance_commute_money_type_id": "m_allowance_commute_money_type",
    "salary_raise_id": "m_salary_raise",
    "holidays_system_id": "m_holidays_system",
    "holidays_breakdown_ids": "m_holiday",
    "english_ids": "m_language_level",
    "insurance_ids": "m_insurance",
    "employment_type_ids": "m_employment_type",
    "employment_period_type_id": "m_employment_period_type",
    "trial_period_id": "m_trial_period",
    "job_charm_details1": "m_job_charm",
    "job_charm_details2": "m_job_charm",
    "job_charm_details3": "m_job_charm",
}
